global:
  inp_dim:
    512
  d_model:
    512
  d_hidden:
    2048 #4 * d_model
  num_heads:
    8
  p_drop:
    0.1 
  Nx:
    6
    
training:
  batch_size:
    3
  lang:
    "mr"
  sent_limit:
    100 # -1 represent no limit
  max_seq_len:
    100